(cl:in-package autoware_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODE-VAL
          MODE
          MAX_WIDTH-VAL
          MAX_WIDTH
          MAX_HEIGHT-VAL
          MAX_HEIGHT
          OFFSET_HSTEP_SIZE-VAL
          OFFSET_HSTEP_SIZE
          OFFSET_VSTEP_SIZE-VAL
          OFFSET_VSTEP_SIZE
          IMAGE_HSTEP_SIZE-VAL
          IMAGE_HSTEP_SIZE
          IMAGE_VSTEP_SIZE-VAL
          IMAGE_VSTEP_SIZE
          PIXEL_FORMAT_BIT_FIELD-VAL
          PIXEL_FORMAT_BIT_FIELD
          VENDOR_PIXEL_FORMAT_BIT_FIELD-VAL
          VENDOR_PIXEL_FORMAT_BIT_FIELD
          PACKET_SIZE-VAL
          PACKET_SIZE
          MIN_PACKET_SIZE-VAL
          MIN_PACKET_SIZE
          MAX_PACKET_SIZE-VAL
          MAX_PACKET_SIZE
          PERCENTAGE-VAL
          PERCENTAGE
))