# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from autoware_can_msgs/MicroBusCan502.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MicroBusCan502(genpy.Message):
  _md5sum = "a1b8e414429b8dde101c01e1b7adae99"
  _type = "autoware_can_msgs/MicroBusCan502"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float64 cycle_time
int16 angle_actual
float64 angle_deg
int16 velocity_actual
int16 velocity_average
int16 velocity_median
int16 acceleration_actual
int16 acceleration_average
int16 acceleration_median
float64 velocity_mps
bool clutch
uint32 read_counter

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','cycle_time','angle_actual','angle_deg','velocity_actual','velocity_average','velocity_median','acceleration_actual','acceleration_average','acceleration_median','velocity_mps','clutch','read_counter']
  _slot_types = ['std_msgs/Header','float64','int16','float64','int16','int16','int16','int16','int16','int16','float64','bool','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cycle_time,angle_actual,angle_deg,velocity_actual,velocity_average,velocity_median,acceleration_actual,acceleration_average,acceleration_median,velocity_mps,clutch,read_counter

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MicroBusCan502, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cycle_time is None:
        self.cycle_time = 0.
      if self.angle_actual is None:
        self.angle_actual = 0
      if self.angle_deg is None:
        self.angle_deg = 0.
      if self.velocity_actual is None:
        self.velocity_actual = 0
      if self.velocity_average is None:
        self.velocity_average = 0
      if self.velocity_median is None:
        self.velocity_median = 0
      if self.acceleration_actual is None:
        self.acceleration_actual = 0
      if self.acceleration_average is None:
        self.acceleration_average = 0
      if self.acceleration_median is None:
        self.acceleration_median = 0
      if self.velocity_mps is None:
        self.velocity_mps = 0.
      if self.clutch is None:
        self.clutch = False
      if self.read_counter is None:
        self.read_counter = 0
    else:
      self.header = std_msgs.msg.Header()
      self.cycle_time = 0.
      self.angle_actual = 0
      self.angle_deg = 0.
      self.velocity_actual = 0
      self.velocity_average = 0
      self.velocity_median = 0
      self.acceleration_actual = 0
      self.acceleration_average = 0
      self.acceleration_median = 0
      self.velocity_mps = 0.
      self.clutch = False
      self.read_counter = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_dhd6hdBI().pack(_x.cycle_time, _x.angle_actual, _x.angle_deg, _x.velocity_actual, _x.velocity_average, _x.velocity_median, _x.acceleration_actual, _x.acceleration_average, _x.acceleration_median, _x.velocity_mps, _x.clutch, _x.read_counter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 43
      (_x.cycle_time, _x.angle_actual, _x.angle_deg, _x.velocity_actual, _x.velocity_average, _x.velocity_median, _x.acceleration_actual, _x.acceleration_average, _x.acceleration_median, _x.velocity_mps, _x.clutch, _x.read_counter,) = _get_struct_dhd6hdBI().unpack(str[start:end])
      self.clutch = bool(self.clutch)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_dhd6hdBI().pack(_x.cycle_time, _x.angle_actual, _x.angle_deg, _x.velocity_actual, _x.velocity_average, _x.velocity_median, _x.acceleration_actual, _x.acceleration_average, _x.acceleration_median, _x.velocity_mps, _x.clutch, _x.read_counter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 43
      (_x.cycle_time, _x.angle_actual, _x.angle_deg, _x.velocity_actual, _x.velocity_average, _x.velocity_median, _x.acceleration_actual, _x.acceleration_average, _x.acceleration_median, _x.velocity_mps, _x.clutch, _x.read_counter,) = _get_struct_dhd6hdBI().unpack(str[start:end])
      self.clutch = bool(self.clutch)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_dhd6hdBI = None
def _get_struct_dhd6hdBI():
    global _struct_dhd6hdBI
    if _struct_dhd6hdBI is None:
        _struct_dhd6hdBI = struct.Struct("<dhd6hdBI")
    return _struct_dhd6hdBI
