// Generated by gencpp from file autoware_can_msgs/MicroBusCan503.msg
// DO NOT EDIT!


#ifndef AUTOWARE_CAN_MSGS_MESSAGE_MICROBUSCAN503_H
#define AUTOWARE_CAN_MSGS_MESSAGE_MICROBUSCAN503_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autoware_can_msgs
{
template <class ContainerAllocator>
struct MicroBusCan503_
{
  typedef MicroBusCan503_<ContainerAllocator> Type;

  MicroBusCan503_()
    : header()
    , pedal_voltage(0)
    , pedal_displacement(0)
    , engine_rotation(0)
    , clutch(false)
    , read_counter(0)  {
    }
  MicroBusCan503_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pedal_voltage(0)
    , pedal_displacement(0)
    , engine_rotation(0)
    , clutch(false)
    , read_counter(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _pedal_voltage_type;
  _pedal_voltage_type pedal_voltage;

   typedef int16_t _pedal_displacement_type;
  _pedal_displacement_type pedal_displacement;

   typedef int16_t _engine_rotation_type;
  _engine_rotation_type engine_rotation;

   typedef uint8_t _clutch_type;
  _clutch_type clutch;

   typedef uint32_t _read_counter_type;
  _read_counter_type read_counter;





  typedef boost::shared_ptr< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> const> ConstPtr;

}; // struct MicroBusCan503_

typedef ::autoware_can_msgs::MicroBusCan503_<std::allocator<void> > MicroBusCan503;

typedef boost::shared_ptr< ::autoware_can_msgs::MicroBusCan503 > MicroBusCan503Ptr;
typedef boost::shared_ptr< ::autoware_can_msgs::MicroBusCan503 const> MicroBusCan503ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'autoware_can_msgs': ['/home/autoware/Autoware_1.11.0_sai_edit/ros/src/msgs/autoware_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
{
  static const char* value()
  {
    return "574e15f63e6b6b35ed4b724a0cd43a84";
  }

  static const char* value(const ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x574e15f63e6b6b35ULL;
  static const uint64_t static_value2 = 0xed4b724a0cd43a84ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_can_msgs/MicroBusCan503";
  }

  static const char* value(const ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 pedal_voltage\n\
int16 pedal_displacement\n\
int16 engine_rotation\n\
bool clutch\n\
uint32 read_counter\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pedal_voltage);
      stream.next(m.pedal_displacement);
      stream.next(m.engine_rotation);
      stream.next(m.clutch);
      stream.next(m.read_counter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MicroBusCan503_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_can_msgs::MicroBusCan503_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pedal_voltage: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pedal_voltage);
    s << indent << "pedal_displacement: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pedal_displacement);
    s << indent << "engine_rotation: ";
    Printer<int16_t>::stream(s, indent + "  ", v.engine_rotation);
    s << indent << "clutch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clutch);
    s << indent << "read_counter: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.read_counter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_CAN_MSGS_MESSAGE_MICROBUSCAN503_H
