// Generated by gencpp from file autoware_msgs/LiesseXZB70MParam.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_LIESSEXZB70MPARAM_H
#define AUTOWARE_MSGS_MESSAGE_LIESSEXZB70MPARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autoware_msgs
{
template <class ContainerAllocator>
struct LiesseXZB70MParam_
{
  typedef LiesseXZB70MParam_<ContainerAllocator> Type;

  LiesseXZB70MParam_()
    : header()
    , shift(0)  {
    }
  LiesseXZB70MParam_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , shift(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _shift_type;
  _shift_type shift;



  enum {
    SHIFT_P = 0,
    SHIFT_R = 1,
    SHIFT_N = 2,
    SHIFT_D = 3,
    SHIFT_4 = 4,
    SHIFT_L = 5,
  };


  typedef boost::shared_ptr< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> const> ConstPtr;

}; // struct LiesseXZB70MParam_

typedef ::autoware_msgs::LiesseXZB70MParam_<std::allocator<void> > LiesseXZB70MParam;

typedef boost::shared_ptr< ::autoware_msgs::LiesseXZB70MParam > LiesseXZB70MParamPtr;
typedef boost::shared_ptr< ::autoware_msgs::LiesseXZB70MParam const> LiesseXZB70MParamConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'autoware_msgs': ['/home/autoware/Autoware_1.11.0_sai_edit/ros/src/msgs/autoware_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "299d9ca4a0f481002204559fa398d19d";
  }

  static const char* value(const ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x299d9ca4a0f48100ULL;
  static const uint64_t static_value2 = 0x2204559fa398d19dULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/LiesseXZB70MParam";
  }

  static const char* value(const ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int8 SHIFT_P = 0\n\
int8 SHIFT_R = 1\n\
int8 SHIFT_N = 2\n\
int8 SHIFT_D = 3\n\
int8 SHIFT_4 = 4\n\
int8 SHIFT_L = 5\n\
int8 shift\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.shift);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiesseXZB70MParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::LiesseXZB70MParam_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "shift: ";
    Printer<int8_t>::stream(s, indent + "  ", v.shift);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_LIESSEXZB70MPARAM_H
