// Generated by gencpp from file autoware_msgs/NdtPoseAndRTKPose.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_NDTPOSEANDRTKPOSE_H
#define AUTOWARE_MSGS_MESSAGE_NDTPOSEANDRTKPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/TwistStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <autoware_msgs/GnssStandardDeviation.h>
#include <autoware_msgs/NDTStat.h>

namespace autoware_msgs
{
template <class ContainerAllocator>
struct NdtPoseAndRTKPose_
{
  typedef NdtPoseAndRTKPose_<ContainerAllocator> Type;

  NdtPoseAndRTKPose_()
    : header()
    , ndt_pose()
    , ndt_localizer_pose()
    , ndt_twist()
    , RTK_pose()
    , RTK_localizer_pose()
    , RTK_standard_deviation()
    , ndt_stat()  {
    }
  NdtPoseAndRTKPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ndt_pose(_alloc)
    , ndt_localizer_pose(_alloc)
    , ndt_twist(_alloc)
    , RTK_pose(_alloc)
    , RTK_localizer_pose(_alloc)
    , RTK_standard_deviation(_alloc)
    , ndt_stat(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _ndt_pose_type;
  _ndt_pose_type ndt_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _ndt_localizer_pose_type;
  _ndt_localizer_pose_type ndt_localizer_pose;

   typedef  ::geometry_msgs::TwistStamped_<ContainerAllocator>  _ndt_twist_type;
  _ndt_twist_type ndt_twist;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _RTK_pose_type;
  _RTK_pose_type RTK_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _RTK_localizer_pose_type;
  _RTK_localizer_pose_type RTK_localizer_pose;

   typedef  ::autoware_msgs::GnssStandardDeviation_<ContainerAllocator>  _RTK_standard_deviation_type;
  _RTK_standard_deviation_type RTK_standard_deviation;

   typedef  ::autoware_msgs::NDTStat_<ContainerAllocator>  _ndt_stat_type;
  _ndt_stat_type ndt_stat;





  typedef boost::shared_ptr< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> const> ConstPtr;

}; // struct NdtPoseAndRTKPose_

typedef ::autoware_msgs::NdtPoseAndRTKPose_<std::allocator<void> > NdtPoseAndRTKPose;

typedef boost::shared_ptr< ::autoware_msgs::NdtPoseAndRTKPose > NdtPoseAndRTKPosePtr;
typedef boost::shared_ptr< ::autoware_msgs::NdtPoseAndRTKPose const> NdtPoseAndRTKPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'jsk_footstep_msgs': ['/opt/ros/kinetic/share/jsk_footstep_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'jsk_recognition_msgs': ['/opt/ros/kinetic/share/jsk_recognition_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'autoware_msgs': ['/home/autoware/Autoware_1.11.0_sai_edit/ros/src/msgs/autoware_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04033cc2ccf6e18ada42ff3baad16dfb";
  }

  static const char* value(const ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04033cc2ccf6e18aULL;
  static const uint64_t static_value2 = 0xda42ff3baad16dfbULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/NdtPoseAndRTKPose";
  }

  static const char* value(const ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/PoseStamped ndt_pose\n\
geometry_msgs/PoseStamped ndt_localizer_pose\n\
geometry_msgs/TwistStamped ndt_twist\n\
geometry_msgs/PoseStamped RTK_pose\n\
geometry_msgs/PoseStamped RTK_localizer_pose\n\
autoware_msgs/GnssStandardDeviation RTK_standard_deviation\n\
autoware_msgs/NDTStat ndt_stat\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistStamped\n\
# A twist with reference coordinate frame and timestamp\n\
Header header\n\
Twist twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: autoware_msgs/GnssStandardDeviation\n\
Header header\n\
float64 lat_std\n\
float64 lon_std\n\
float64 alt_std\n\
\n\
================================================================================\n\
MSG: autoware_msgs/NDTStat\n\
Header header\n\
float32 exe_time\n\
int32 iteration\n\
float32 score\n\
float32 velocity\n\
float32 acceleration\n\
int32 use_predict_pose\n\
";
  }

  static const char* value(const ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ndt_pose);
      stream.next(m.ndt_localizer_pose);
      stream.next(m.ndt_twist);
      stream.next(m.RTK_pose);
      stream.next(m.RTK_localizer_pose);
      stream.next(m.RTK_standard_deviation);
      stream.next(m.ndt_stat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NdtPoseAndRTKPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::NdtPoseAndRTKPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ndt_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ndt_pose);
    s << indent << "ndt_localizer_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ndt_localizer_pose);
    s << indent << "ndt_twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ndt_twist);
    s << indent << "RTK_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.RTK_pose);
    s << indent << "RTK_localizer_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.RTK_localizer_pose);
    s << indent << "RTK_standard_deviation: ";
    s << std::endl;
    Printer< ::autoware_msgs::GnssStandardDeviation_<ContainerAllocator> >::stream(s, indent + "  ", v.RTK_standard_deviation);
    s << indent << "ndt_stat: ";
    s << std::endl;
    Printer< ::autoware_msgs::NDTStat_<ContainerAllocator> >::stream(s, indent + "  ", v.ndt_stat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_NDTPOSEANDRTKPOSE_H
