// Generated by gencpp from file autoware_config_msgs/ConfigManualDriveStroke.msg
// DO NOT EDIT!


#ifndef AUTOWARE_CONFIG_MSGS_MESSAGE_CONFIGMANUALDRIVESTROKE_H
#define AUTOWARE_CONFIG_MSGS_MESSAGE_CONFIGMANUALDRIVESTROKE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autoware_config_msgs
{
template <class ContainerAllocator>
struct ConfigManualDriveStroke_
{
  typedef ConfigManualDriveStroke_<ContainerAllocator> Type;

  ConfigManualDriveStroke_()
    : header()
    , run(false)
    , drive_stroke(0.0)
    , brake_stroke(0.0)  {
    }
  ConfigManualDriveStroke_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , run(false)
    , drive_stroke(0.0)
    , brake_stroke(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _run_type;
  _run_type run;

   typedef double _drive_stroke_type;
  _drive_stroke_type drive_stroke;

   typedef double _brake_stroke_type;
  _brake_stroke_type brake_stroke;





  typedef boost::shared_ptr< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigManualDriveStroke_

typedef ::autoware_config_msgs::ConfigManualDriveStroke_<std::allocator<void> > ConfigManualDriveStroke;

typedef boost::shared_ptr< ::autoware_config_msgs::ConfigManualDriveStroke > ConfigManualDriveStrokePtr;
typedef boost::shared_ptr< ::autoware_config_msgs::ConfigManualDriveStroke const> ConfigManualDriveStrokeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autoware_config_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'autoware_config_msgs': ['/home/autoware/Autoware_1.11.0_sai_edit/ros/src/msgs/autoware_config_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac436a8678a2221c76afb687b9d38a53";
  }

  static const char* value(const ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac436a8678a2221cULL;
  static const uint64_t static_value2 = 0x76afb687b9d38a53ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_config_msgs/ConfigManualDriveStroke";
  }

  static const char* value(const ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool run\n\
float64 drive_stroke\n\
float64 brake_stroke\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.run);
      stream.next(m.drive_stroke);
      stream.next(m.brake_stroke);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigManualDriveStroke_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_config_msgs::ConfigManualDriveStroke_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
    s << indent << "drive_stroke: ";
    Printer<double>::stream(s, indent + "  ", v.drive_stroke);
    s << indent << "brake_stroke: ";
    Printer<double>::stream(s, indent + "  ", v.brake_stroke);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_CONFIG_MSGS_MESSAGE_CONFIGMANUALDRIVESTROKE_H
