/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QGroupBox *groupBox_drive;
    QLabel *lb_drive_mode;
    QLabel *lb_drive_control_mode;
    QLabel *lb_drive_input_mode;
    QTextEdit *tx_drive_mode;
    QTextEdit *tx_drive_control_mode;
    QTextEdit *tx_drive_input_mode;
    QPushButton *bt_drive_mode_manual;
    QPushButton *bt_drive_mode_program;
    QPushButton *bt_drive_control_mode_velocity;
    QPushButton *bt_drive_control_mode_stroke;
    QPushButton *bt_drive_input_mode_direct;
    QPushButton *bt_drive_input_mode_autoware;
    QGroupBox *gb_stroke;
    QSpinBox *spin_stroke_input;
    QSlider *hS_stroke_input;
    QLabel *lb_stroke_target;
    QTextEdit *tx_stroke_target;
    QTextEdit *tx_stroke_actual;
    QLabel *lb_stroke_actual;
    QLabel *lb_drive_clutch;
    QTextEdit *tx_drive_clutch;
    QPushButton *bt_drive_clutch_cut;
    QPushButton *bt_drive_clutch_connect;
    QGroupBox *groupBox_other_2;
    QTextEdit *tx_ndt_distance_check;
    QTextEdit *tx_ndt_angular_check;
    QTextEdit *tx_gnss_distance_check;
    QTextEdit *tx_gnss_angular_check;
    QLabel *lb_waypoint_num;
    QTextEdit *tx_waypoint_num;
    QLabel *lb_stroke_routine;
    QTextEdit *tx_stroke_routine;
    QLabel *lb_yaw;
    QTextEdit *tx_yaw;
    QLabel *lb_roll;
    QTextEdit *tx_roll;
    QLabel *lb_pitch;
    QTextEdit *tx_pitch;
    QGroupBox *groupBox_steer;
    QLabel *lb_steer_mode;
    QLabel *lb_steer_input_mod;
    QTextEdit *tx_steer_mode;
    QTextEdit *tx_steer_input_mode;
    QPushButton *bt_steer_mode_manual;
    QPushButton *bt_steer_mode_program;
    QPushButton *bt_steer_input_mode_direct;
    QPushButton *bt_steer_input_mode_autoware;
    QGroupBox *gb_angle;
    QSpinBox *spin_angle_input;
    QSlider *hS_angle_input;
    QLabel *lb_angle_target;
    QTextEdit *tx_angle_target;
    QTextEdit *tx_angle_actual;
    QLabel *lb_angle_actual;
    QLabel *lb_steer_clutch;
    QTextEdit *tx_steer_clutch;
    QPushButton *bt_steer_clutch_cut;
    QPushButton *bt_steer_clutch_connect;
    QGroupBox *groupBox_other;
    QLabel *lb_blinker_right;
    QPushButton *bt_blinker_right_on;
    QPushButton *bt_blinker_right_off;
    QLabel *lb_blinker_left;
    QPushButton *bt_blinker_left_on;
    QPushButton *bt_blinker_left_off;
    QTextEdit *tx_error_text;
    QLabel *lb_error_text;
    QPushButton *bt_error_text_reset;
    QTextEdit *tx_distance_check;
    QTextEdit *tx_angular_check;
    QLabel *lb_stopper_distance;
    QTextEdit *tx_stopper_distance;
    QLabel *lb_can_jurk;
    QTextEdit *tx_can_jurk;
    QTextEdit *tx_can_accel;
    QLabel *lb_can_velocity;
    QTextEdit *tx_can_velocity;
    QLabel *lb_can_accel;
    QLabel *lb_lat;
    QTextEdit *tx_lat;
    QTextEdit *tx_lon;
    QLabel *lb_lon;
    QTextEdit *tx_alt;
    QLabel *lb_alt;
    QLabel *lb_ndt_score;
    QTextEdit *tx_ndt_score;
    QLabel *lb_ndt_ok;
    QTextEdit *tx_ndt_ok;
    QLabel *lb_gnss_ok;
    QTextEdit *tx_gnss_ok;
    QLabel *lb_localizer_select;
    QTextEdit *tx_localizer_select;
    QTextEdit *tx_localizer_match_stat;
    QLabel *lb_localizer_match_stat;
    QWidget *tab_2;
    QPushButton *bt_emergency_clear;
    QGroupBox *gb_shift;
    QPushButton *bt_shift_P;
    QPushButton *bt_shift_R;
    QPushButton *bt_shift_D;
    QPushButton *bt_shift_N;
    QPushButton *bt_shift_4;
    QPushButton *bt_shift_2L;
    QGroupBox *gb_velocity;
    QSpinBox *spin_velocity_input;
    QSlider *hS_velocity_input;
    QLabel *lb_velocity_target;
    QTextEdit *tx_velocity_target;
    QTextEdit *tx_velocity_actual;
    QLabel *lb_velocity_actual;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1066, 738);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 30, 691, 641));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox_drive = new QGroupBox(tab);
        groupBox_drive->setObjectName(QStringLiteral("groupBox_drive"));
        groupBox_drive->setEnabled(true);
        groupBox_drive->setGeometry(QRect(10, 10, 331, 491));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(238, 238, 236, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_drive->setPalette(palette);
        groupBox_drive->setAutoFillBackground(true);
        lb_drive_mode = new QLabel(groupBox_drive);
        lb_drive_mode->setObjectName(QStringLiteral("lb_drive_mode"));
        lb_drive_mode->setGeometry(QRect(10, 40, 91, 17));
        lb_drive_control_mode = new QLabel(groupBox_drive);
        lb_drive_control_mode->setObjectName(QStringLiteral("lb_drive_control_mode"));
        lb_drive_control_mode->setGeometry(QRect(10, 80, 101, 16));
        lb_drive_input_mode = new QLabel(groupBox_drive);
        lb_drive_input_mode->setObjectName(QStringLiteral("lb_drive_input_mode"));
        lb_drive_input_mode->setGeometry(QRect(10, 110, 101, 17));
        tx_drive_mode = new QTextEdit(groupBox_drive);
        tx_drive_mode->setObjectName(QStringLiteral("tx_drive_mode"));
        tx_drive_mode->setGeometry(QRect(110, 40, 71, 21));
        tx_drive_mode->setAutoFillBackground(true);
        tx_drive_mode->setLineWidth(0);
        tx_drive_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_mode->setReadOnly(true);
        tx_drive_mode->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_drive_control_mode = new QTextEdit(groupBox_drive);
        tx_drive_control_mode->setObjectName(QStringLiteral("tx_drive_control_mode"));
        tx_drive_control_mode->setGeometry(QRect(110, 80, 71, 21));
        tx_drive_control_mode->setLineWidth(0);
        tx_drive_control_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_control_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_control_mode->setReadOnly(true);
        tx_drive_input_mode = new QTextEdit(groupBox_drive);
        tx_drive_input_mode->setObjectName(QStringLiteral("tx_drive_input_mode"));
        tx_drive_input_mode->setGeometry(QRect(110, 110, 71, 21));
        tx_drive_input_mode->setLineWidth(0);
        tx_drive_input_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_input_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_input_mode->setReadOnly(true);
        bt_drive_mode_manual = new QPushButton(groupBox_drive);
        bt_drive_mode_manual->setObjectName(QStringLiteral("bt_drive_mode_manual"));
        bt_drive_mode_manual->setEnabled(false);
        bt_drive_mode_manual->setGeometry(QRect(190, 40, 61, 25));
        bt_drive_mode_program = new QPushButton(groupBox_drive);
        bt_drive_mode_program->setObjectName(QStringLiteral("bt_drive_mode_program"));
        bt_drive_mode_program->setEnabled(false);
        bt_drive_mode_program->setGeometry(QRect(260, 40, 61, 25));
        bt_drive_control_mode_velocity = new QPushButton(groupBox_drive);
        bt_drive_control_mode_velocity->setObjectName(QStringLiteral("bt_drive_control_mode_velocity"));
        bt_drive_control_mode_velocity->setEnabled(false);
        bt_drive_control_mode_velocity->setGeometry(QRect(190, 80, 61, 25));
        bt_drive_control_mode_stroke = new QPushButton(groupBox_drive);
        bt_drive_control_mode_stroke->setObjectName(QStringLiteral("bt_drive_control_mode_stroke"));
        bt_drive_control_mode_stroke->setEnabled(false);
        bt_drive_control_mode_stroke->setGeometry(QRect(260, 80, 61, 25));
        bt_drive_input_mode_direct = new QPushButton(groupBox_drive);
        bt_drive_input_mode_direct->setObjectName(QStringLiteral("bt_drive_input_mode_direct"));
        bt_drive_input_mode_direct->setEnabled(false);
        bt_drive_input_mode_direct->setGeometry(QRect(190, 110, 61, 25));
        bt_drive_input_mode_autoware = new QPushButton(groupBox_drive);
        bt_drive_input_mode_autoware->setObjectName(QStringLiteral("bt_drive_input_mode_autoware"));
        bt_drive_input_mode_autoware->setEnabled(false);
        bt_drive_input_mode_autoware->setGeometry(QRect(260, 110, 61, 25));
        gb_stroke = new QGroupBox(groupBox_drive);
        gb_stroke->setObjectName(QStringLiteral("gb_stroke"));
        gb_stroke->setEnabled(true);
        gb_stroke->setGeometry(QRect(10, 170, 311, 91));
        QPalette palette1;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush3(QColor(186, 189, 182, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush);
        QBrush brush4(QColor(220, 222, 218, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        QBrush brush5(QColor(93, 94, 91, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush5);
        QBrush brush6(QColor(124, 126, 121, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        QBrush brush8(QColor(0, 0, 0, 128));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_stroke->setPalette(palette1);
        gb_stroke->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_stroke->setAcceptDrops(false);
        gb_stroke->setAutoFillBackground(true);
        gb_stroke->setFlat(false);
        gb_stroke->setCheckable(false);
        spin_stroke_input = new QSpinBox(gb_stroke);
        spin_stroke_input->setObjectName(QStringLiteral("spin_stroke_input"));
        spin_stroke_input->setEnabled(false);
        spin_stroke_input->setGeometry(QRect(60, 30, 61, 26));
        hS_stroke_input = new QSlider(gb_stroke);
        hS_stroke_input->setObjectName(QStringLiteral("hS_stroke_input"));
        hS_stroke_input->setEnabled(false);
        hS_stroke_input->setGeometry(QRect(10, 70, 160, 16));
        hS_stroke_input->setOrientation(Qt::Horizontal);
        lb_stroke_target = new QLabel(gb_stroke);
        lb_stroke_target->setObjectName(QStringLiteral("lb_stroke_target"));
        lb_stroke_target->setGeometry(QRect(180, 30, 101, 17));
        tx_stroke_target = new QTextEdit(gb_stroke);
        tx_stroke_target->setObjectName(QStringLiteral("tx_stroke_target"));
        tx_stroke_target->setGeometry(QRect(230, 30, 71, 21));
        tx_stroke_target->setLineWidth(0);
        tx_stroke_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_target->setReadOnly(true);
        tx_stroke_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_stroke_actual = new QTextEdit(gb_stroke);
        tx_stroke_actual->setObjectName(QStringLiteral("tx_stroke_actual"));
        tx_stroke_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_stroke_actual->setLineWidth(0);
        tx_stroke_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_actual->setReadOnly(true);
        tx_stroke_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_stroke_actual = new QLabel(gb_stroke);
        lb_stroke_actual->setObjectName(QStringLiteral("lb_stroke_actual"));
        lb_stroke_actual->setGeometry(QRect(180, 60, 101, 17));
        lb_drive_clutch = new QLabel(groupBox_drive);
        lb_drive_clutch->setObjectName(QStringLiteral("lb_drive_clutch"));
        lb_drive_clutch->setGeometry(QRect(10, 140, 101, 17));
        tx_drive_clutch = new QTextEdit(groupBox_drive);
        tx_drive_clutch->setObjectName(QStringLiteral("tx_drive_clutch"));
        tx_drive_clutch->setGeometry(QRect(110, 140, 71, 21));
        tx_drive_clutch->setLineWidth(0);
        tx_drive_clutch->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_clutch->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_drive_clutch->setReadOnly(true);
        bt_drive_clutch_cut = new QPushButton(groupBox_drive);
        bt_drive_clutch_cut->setObjectName(QStringLiteral("bt_drive_clutch_cut"));
        bt_drive_clutch_cut->setEnabled(false);
        bt_drive_clutch_cut->setGeometry(QRect(190, 140, 61, 25));
        bt_drive_clutch_connect = new QPushButton(groupBox_drive);
        bt_drive_clutch_connect->setObjectName(QStringLiteral("bt_drive_clutch_connect"));
        bt_drive_clutch_connect->setEnabled(false);
        bt_drive_clutch_connect->setGeometry(QRect(260, 140, 61, 25));
        groupBox_other_2 = new QGroupBox(groupBox_drive);
        groupBox_other_2->setObjectName(QStringLiteral("groupBox_other_2"));
        groupBox_other_2->setEnabled(true);
        groupBox_other_2->setGeometry(QRect(10, 270, 311, 211));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_other_2->setPalette(palette2);
        groupBox_other_2->setAutoFillBackground(true);
        tx_ndt_distance_check = new QTextEdit(groupBox_other_2);
        tx_ndt_distance_check->setObjectName(QStringLiteral("tx_ndt_distance_check"));
        tx_ndt_distance_check->setGeometry(QRect(0, 20, 151, 51));
        QFont font;
        font.setPointSize(14);
        tx_ndt_distance_check->setFont(font);
        tx_ndt_distance_check->setAutoFillBackground(true);
        tx_ndt_distance_check->setLineWidth(0);
        tx_ndt_distance_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_distance_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_distance_check->setReadOnly(true);
        tx_ndt_distance_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_ndt_angular_check = new QTextEdit(groupBox_other_2);
        tx_ndt_angular_check->setObjectName(QStringLiteral("tx_ndt_angular_check"));
        tx_ndt_angular_check->setGeometry(QRect(160, 20, 151, 51));
        tx_ndt_angular_check->setFont(font);
        tx_ndt_angular_check->setAutoFillBackground(true);
        tx_ndt_angular_check->setLineWidth(0);
        tx_ndt_angular_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_angular_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_angular_check->setReadOnly(true);
        tx_ndt_angular_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_gnss_distance_check = new QTextEdit(groupBox_other_2);
        tx_gnss_distance_check->setObjectName(QStringLiteral("tx_gnss_distance_check"));
        tx_gnss_distance_check->setGeometry(QRect(0, 80, 151, 51));
        tx_gnss_distance_check->setFont(font);
        tx_gnss_distance_check->setAutoFillBackground(true);
        tx_gnss_distance_check->setLineWidth(0);
        tx_gnss_distance_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_distance_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_distance_check->setReadOnly(true);
        tx_gnss_distance_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_gnss_angular_check = new QTextEdit(groupBox_other_2);
        tx_gnss_angular_check->setObjectName(QStringLiteral("tx_gnss_angular_check"));
        tx_gnss_angular_check->setGeometry(QRect(160, 80, 151, 51));
        tx_gnss_angular_check->setFont(font);
        tx_gnss_angular_check->setAutoFillBackground(true);
        tx_gnss_angular_check->setLineWidth(0);
        tx_gnss_angular_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_angular_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_angular_check->setReadOnly(true);
        tx_gnss_angular_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_waypoint_num = new QLabel(groupBox_other_2);
        lb_waypoint_num->setObjectName(QStringLiteral("lb_waypoint_num"));
        lb_waypoint_num->setGeometry(QRect(0, 140, 66, 17));
        tx_waypoint_num = new QTextEdit(groupBox_other_2);
        tx_waypoint_num->setObjectName(QStringLiteral("tx_waypoint_num"));
        tx_waypoint_num->setGeometry(QRect(70, 130, 81, 31));
        tx_waypoint_num->setFont(font);
        tx_waypoint_num->setAutoFillBackground(true);
        tx_waypoint_num->setLineWidth(0);
        tx_waypoint_num->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_waypoint_num->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_waypoint_num->setReadOnly(true);
        tx_waypoint_num->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_stroke_routine = new QLabel(groupBox_other_2);
        lb_stroke_routine->setObjectName(QStringLiteral("lb_stroke_routine"));
        lb_stroke_routine->setGeometry(QRect(160, 140, 66, 17));
        lb_stroke_routine->setTextFormat(Qt::AutoText);
        tx_stroke_routine = new QTextEdit(groupBox_other_2);
        tx_stroke_routine->setObjectName(QStringLiteral("tx_stroke_routine"));
        tx_stroke_routine->setGeometry(QRect(230, 130, 81, 31));
        tx_stroke_routine->setFont(font);
        tx_stroke_routine->setAutoFillBackground(true);
        tx_stroke_routine->setLineWidth(0);
        tx_stroke_routine->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_routine->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stroke_routine->setReadOnly(true);
        tx_stroke_routine->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_yaw = new QLabel(groupBox_other_2);
        lb_yaw->setObjectName(QStringLiteral("lb_yaw"));
        lb_yaw->setGeometry(QRect(0, 165, 41, 17));
        tx_yaw = new QTextEdit(groupBox_other_2);
        tx_yaw->setObjectName(QStringLiteral("tx_yaw"));
        tx_yaw->setGeometry(QRect(30, 160, 61, 31));
        tx_yaw->setFont(font);
        tx_yaw->setAutoFillBackground(true);
        tx_yaw->setLineWidth(0);
        tx_yaw->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_yaw->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_yaw->setReadOnly(true);
        tx_yaw->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_roll = new QLabel(groupBox_other_2);
        lb_roll->setObjectName(QStringLiteral("lb_roll"));
        lb_roll->setGeometry(QRect(95, 165, 41, 17));
        tx_roll = new QTextEdit(groupBox_other_2);
        tx_roll->setObjectName(QStringLiteral("tx_roll"));
        tx_roll->setGeometry(QRect(120, 160, 61, 31));
        tx_roll->setFont(font);
        tx_roll->setAutoFillBackground(true);
        tx_roll->setLineWidth(0);
        tx_roll->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_roll->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_roll->setReadOnly(true);
        tx_roll->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_pitch = new QLabel(groupBox_other_2);
        lb_pitch->setObjectName(QStringLiteral("lb_pitch"));
        lb_pitch->setGeometry(QRect(185, 165, 41, 17));
        tx_pitch = new QTextEdit(groupBox_other_2);
        tx_pitch->setObjectName(QStringLiteral("tx_pitch"));
        tx_pitch->setGeometry(QRect(225, 160, 61, 31));
        tx_pitch->setFont(font);
        tx_pitch->setAutoFillBackground(true);
        tx_pitch->setLineWidth(0);
        tx_pitch->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_pitch->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_pitch->setReadOnly(true);
        tx_pitch->setTextInteractionFlags(Qt::TextSelectableByMouse);
        groupBox_steer = new QGroupBox(tab);
        groupBox_steer->setObjectName(QStringLiteral("groupBox_steer"));
        groupBox_steer->setEnabled(true);
        groupBox_steer->setGeometry(QRect(350, 10, 331, 241));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_steer->setPalette(palette3);
        groupBox_steer->setAutoFillBackground(true);
        lb_steer_mode = new QLabel(groupBox_steer);
        lb_steer_mode->setObjectName(QStringLiteral("lb_steer_mode"));
        lb_steer_mode->setGeometry(QRect(10, 40, 91, 17));
        lb_steer_input_mod = new QLabel(groupBox_steer);
        lb_steer_input_mod->setObjectName(QStringLiteral("lb_steer_input_mod"));
        lb_steer_input_mod->setGeometry(QRect(10, 80, 101, 17));
        tx_steer_mode = new QTextEdit(groupBox_steer);
        tx_steer_mode->setObjectName(QStringLiteral("tx_steer_mode"));
        tx_steer_mode->setGeometry(QRect(120, 40, 61, 21));
        tx_steer_mode->setAutoFillBackground(true);
        tx_steer_mode->setLineWidth(0);
        tx_steer_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_mode->setReadOnly(true);
        tx_steer_mode->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_steer_input_mode = new QTextEdit(groupBox_steer);
        tx_steer_input_mode->setObjectName(QStringLiteral("tx_steer_input_mode"));
        tx_steer_input_mode->setGeometry(QRect(110, 80, 71, 21));
        tx_steer_input_mode->setLineWidth(0);
        tx_steer_input_mode->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_input_mode->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_input_mode->setReadOnly(true);
        bt_steer_mode_manual = new QPushButton(groupBox_steer);
        bt_steer_mode_manual->setObjectName(QStringLiteral("bt_steer_mode_manual"));
        bt_steer_mode_manual->setEnabled(false);
        bt_steer_mode_manual->setGeometry(QRect(190, 40, 61, 25));
        bt_steer_mode_program = new QPushButton(groupBox_steer);
        bt_steer_mode_program->setObjectName(QStringLiteral("bt_steer_mode_program"));
        bt_steer_mode_program->setEnabled(false);
        bt_steer_mode_program->setGeometry(QRect(260, 40, 61, 25));
        bt_steer_input_mode_direct = new QPushButton(groupBox_steer);
        bt_steer_input_mode_direct->setObjectName(QStringLiteral("bt_steer_input_mode_direct"));
        bt_steer_input_mode_direct->setEnabled(false);
        bt_steer_input_mode_direct->setGeometry(QRect(190, 80, 61, 25));
        bt_steer_input_mode_autoware = new QPushButton(groupBox_steer);
        bt_steer_input_mode_autoware->setObjectName(QStringLiteral("bt_steer_input_mode_autoware"));
        bt_steer_input_mode_autoware->setEnabled(false);
        bt_steer_input_mode_autoware->setGeometry(QRect(260, 80, 61, 25));
        gb_angle = new QGroupBox(groupBox_steer);
        gb_angle->setObjectName(QStringLiteral("gb_angle"));
        gb_angle->setEnabled(true);
        gb_angle->setGeometry(QRect(10, 140, 311, 91));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_angle->setPalette(palette4);
        gb_angle->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_angle->setAcceptDrops(false);
        gb_angle->setAutoFillBackground(true);
        gb_angle->setFlat(false);
        gb_angle->setCheckable(false);
        spin_angle_input = new QSpinBox(gb_angle);
        spin_angle_input->setObjectName(QStringLiteral("spin_angle_input"));
        spin_angle_input->setEnabled(false);
        spin_angle_input->setGeometry(QRect(60, 30, 61, 26));
        hS_angle_input = new QSlider(gb_angle);
        hS_angle_input->setObjectName(QStringLiteral("hS_angle_input"));
        hS_angle_input->setEnabled(false);
        hS_angle_input->setGeometry(QRect(10, 70, 160, 16));
        hS_angle_input->setOrientation(Qt::Horizontal);
        lb_angle_target = new QLabel(gb_angle);
        lb_angle_target->setObjectName(QStringLiteral("lb_angle_target"));
        lb_angle_target->setGeometry(QRect(180, 30, 101, 17));
        tx_angle_target = new QTextEdit(gb_angle);
        tx_angle_target->setObjectName(QStringLiteral("tx_angle_target"));
        tx_angle_target->setGeometry(QRect(230, 30, 71, 21));
        tx_angle_target->setLineWidth(0);
        tx_angle_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_target->setReadOnly(true);
        tx_angle_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_angle_actual = new QTextEdit(gb_angle);
        tx_angle_actual->setObjectName(QStringLiteral("tx_angle_actual"));
        tx_angle_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_angle_actual->setLineWidth(0);
        tx_angle_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angle_actual->setReadOnly(true);
        tx_angle_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_angle_actual = new QLabel(gb_angle);
        lb_angle_actual->setObjectName(QStringLiteral("lb_angle_actual"));
        lb_angle_actual->setGeometry(QRect(180, 60, 101, 17));
        lb_steer_clutch = new QLabel(groupBox_steer);
        lb_steer_clutch->setObjectName(QStringLiteral("lb_steer_clutch"));
        lb_steer_clutch->setGeometry(QRect(10, 110, 101, 17));
        tx_steer_clutch = new QTextEdit(groupBox_steer);
        tx_steer_clutch->setObjectName(QStringLiteral("tx_steer_clutch"));
        tx_steer_clutch->setGeometry(QRect(110, 110, 71, 21));
        tx_steer_clutch->setLineWidth(0);
        tx_steer_clutch->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_clutch->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_steer_clutch->setReadOnly(true);
        bt_steer_clutch_cut = new QPushButton(groupBox_steer);
        bt_steer_clutch_cut->setObjectName(QStringLiteral("bt_steer_clutch_cut"));
        bt_steer_clutch_cut->setEnabled(false);
        bt_steer_clutch_cut->setGeometry(QRect(190, 110, 61, 25));
        bt_steer_clutch_connect = new QPushButton(groupBox_steer);
        bt_steer_clutch_connect->setObjectName(QStringLiteral("bt_steer_clutch_connect"));
        bt_steer_clutch_connect->setEnabled(false);
        bt_steer_clutch_connect->setGeometry(QRect(260, 110, 61, 25));
        groupBox_other = new QGroupBox(tab);
        groupBox_other->setObjectName(QStringLiteral("groupBox_other"));
        groupBox_other->setEnabled(true);
        groupBox_other->setGeometry(QRect(350, 260, 331, 351));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        groupBox_other->setPalette(palette5);
        groupBox_other->setAutoFillBackground(true);
        lb_blinker_right = new QLabel(groupBox_other);
        lb_blinker_right->setObjectName(QStringLiteral("lb_blinker_right"));
        lb_blinker_right->setGeometry(QRect(10, 30, 91, 17));
        bt_blinker_right_on = new QPushButton(groupBox_other);
        bt_blinker_right_on->setObjectName(QStringLiteral("bt_blinker_right_on"));
        bt_blinker_right_on->setEnabled(false);
        bt_blinker_right_on->setGeometry(QRect(110, 30, 61, 25));
        bt_blinker_right_off = new QPushButton(groupBox_other);
        bt_blinker_right_off->setObjectName(QStringLiteral("bt_blinker_right_off"));
        bt_blinker_right_off->setEnabled(false);
        bt_blinker_right_off->setGeometry(QRect(180, 30, 61, 25));
        lb_blinker_left = new QLabel(groupBox_other);
        lb_blinker_left->setObjectName(QStringLiteral("lb_blinker_left"));
        lb_blinker_left->setGeometry(QRect(10, 60, 91, 17));
        bt_blinker_left_on = new QPushButton(groupBox_other);
        bt_blinker_left_on->setObjectName(QStringLiteral("bt_blinker_left_on"));
        bt_blinker_left_on->setEnabled(false);
        bt_blinker_left_on->setGeometry(QRect(110, 60, 61, 25));
        bt_blinker_left_off = new QPushButton(groupBox_other);
        bt_blinker_left_off->setObjectName(QStringLiteral("bt_blinker_left_off"));
        bt_blinker_left_off->setEnabled(false);
        bt_blinker_left_off->setGeometry(QRect(180, 60, 61, 25));
        tx_error_text = new QTextEdit(groupBox_other);
        tx_error_text->setObjectName(QStringLiteral("tx_error_text"));
        tx_error_text->setGeometry(QRect(110, 190, 211, 41));
        tx_error_text->setAutoFillBackground(true);
        tx_error_text->setLineWidth(0);
        tx_error_text->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_error_text->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_error_text->setReadOnly(true);
        tx_error_text->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_error_text = new QLabel(groupBox_other);
        lb_error_text->setObjectName(QStringLiteral("lb_error_text"));
        lb_error_text->setGeometry(QRect(10, 200, 91, 17));
        bt_error_text_reset = new QPushButton(groupBox_other);
        bt_error_text_reset->setObjectName(QStringLiteral("bt_error_text_reset"));
        bt_error_text_reset->setGeometry(QRect(240, 140, 81, 41));
        tx_distance_check = new QTextEdit(groupBox_other);
        tx_distance_check->setObjectName(QStringLiteral("tx_distance_check"));
        tx_distance_check->setGeometry(QRect(10, 240, 151, 51));
        tx_distance_check->setFont(font);
        tx_distance_check->setAutoFillBackground(true);
        tx_distance_check->setLineWidth(0);
        tx_distance_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_distance_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_distance_check->setReadOnly(true);
        tx_distance_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_angular_check = new QTextEdit(groupBox_other);
        tx_angular_check->setObjectName(QStringLiteral("tx_angular_check"));
        tx_angular_check->setGeometry(QRect(170, 240, 151, 51));
        tx_angular_check->setFont(font);
        tx_angular_check->setAutoFillBackground(true);
        tx_angular_check->setLineWidth(0);
        tx_angular_check->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angular_check->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_angular_check->setReadOnly(true);
        tx_angular_check->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_stopper_distance = new QLabel(groupBox_other);
        lb_stopper_distance->setObjectName(QStringLiteral("lb_stopper_distance"));
        lb_stopper_distance->setGeometry(QRect(10, 300, 66, 17));
        tx_stopper_distance = new QTextEdit(groupBox_other);
        tx_stopper_distance->setObjectName(QStringLiteral("tx_stopper_distance"));
        tx_stopper_distance->setGeometry(QRect(60, 290, 101, 31));
        tx_stopper_distance->setFont(font);
        tx_stopper_distance->setAutoFillBackground(true);
        tx_stopper_distance->setLineWidth(0);
        tx_stopper_distance->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stopper_distance->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_stopper_distance->setReadOnly(true);
        tx_stopper_distance->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_can_jurk = new QLabel(groupBox_other);
        lb_can_jurk->setObjectName(QStringLiteral("lb_can_jurk"));
        lb_can_jurk->setGeometry(QRect(170, 330, 66, 17));
        tx_can_jurk = new QTextEdit(groupBox_other);
        tx_can_jurk->setObjectName(QStringLiteral("tx_can_jurk"));
        tx_can_jurk->setGeometry(QRect(220, 320, 101, 31));
        tx_can_jurk->setFont(font);
        tx_can_jurk->setAutoFillBackground(true);
        tx_can_jurk->setLineWidth(0);
        tx_can_jurk->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_jurk->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_jurk->setReadOnly(true);
        tx_can_jurk->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_can_accel = new QTextEdit(groupBox_other);
        tx_can_accel->setObjectName(QStringLiteral("tx_can_accel"));
        tx_can_accel->setGeometry(QRect(60, 320, 101, 31));
        tx_can_accel->setFont(font);
        tx_can_accel->setAutoFillBackground(true);
        tx_can_accel->setLineWidth(0);
        tx_can_accel->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_accel->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_accel->setReadOnly(true);
        tx_can_accel->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_can_velocity = new QLabel(groupBox_other);
        lb_can_velocity->setObjectName(QStringLiteral("lb_can_velocity"));
        lb_can_velocity->setGeometry(QRect(170, 300, 66, 17));
        tx_can_velocity = new QTextEdit(groupBox_other);
        tx_can_velocity->setObjectName(QStringLiteral("tx_can_velocity"));
        tx_can_velocity->setGeometry(QRect(220, 290, 101, 31));
        tx_can_velocity->setFont(font);
        tx_can_velocity->setAutoFillBackground(true);
        tx_can_velocity->setLineWidth(0);
        tx_can_velocity->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_velocity->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_can_velocity->setReadOnly(true);
        tx_can_velocity->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_can_accel = new QLabel(groupBox_other);
        lb_can_accel->setObjectName(QStringLiteral("lb_can_accel"));
        lb_can_accel->setGeometry(QRect(10, 330, 66, 17));
        lb_lat = new QLabel(groupBox_other);
        lb_lat->setObjectName(QStringLiteral("lb_lat"));
        lb_lat->setGeometry(QRect(10, 100, 21, 17));
        tx_lat = new QTextEdit(groupBox_other);
        tx_lat->setObjectName(QStringLiteral("tx_lat"));
        tx_lat->setGeometry(QRect(30, 90, 71, 31));
        tx_lat->setAutoFillBackground(true);
        tx_lat->setLineWidth(0);
        tx_lat->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_lat->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_lat->setReadOnly(true);
        tx_lat->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_lon = new QTextEdit(groupBox_other);
        tx_lon->setObjectName(QStringLiteral("tx_lon"));
        tx_lon->setGeometry(QRect(130, 90, 71, 31));
        tx_lon->setAutoFillBackground(true);
        tx_lon->setLineWidth(0);
        tx_lon->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_lon->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_lon->setReadOnly(true);
        tx_lon->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_lon = new QLabel(groupBox_other);
        lb_lon->setObjectName(QStringLiteral("lb_lon"));
        lb_lon->setGeometry(QRect(110, 100, 21, 17));
        tx_alt = new QTextEdit(groupBox_other);
        tx_alt->setObjectName(QStringLiteral("tx_alt"));
        tx_alt->setGeometry(QRect(230, 90, 71, 31));
        tx_alt->setAutoFillBackground(true);
        tx_alt->setLineWidth(0);
        tx_alt->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_alt->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_alt->setReadOnly(true);
        tx_alt->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_alt = new QLabel(groupBox_other);
        lb_alt->setObjectName(QStringLiteral("lb_alt"));
        lb_alt->setGeometry(QRect(210, 100, 21, 17));
        lb_ndt_score = new QLabel(groupBox_other);
        lb_ndt_score->setObjectName(QStringLiteral("lb_ndt_score"));
        lb_ndt_score->setGeometry(QRect(10, 130, 71, 17));
        tx_ndt_score = new QTextEdit(groupBox_other);
        tx_ndt_score->setObjectName(QStringLiteral("tx_ndt_score"));
        tx_ndt_score->setGeometry(QRect(75, 120, 71, 31));
        tx_ndt_score->setAutoFillBackground(true);
        tx_ndt_score->setLineWidth(0);
        tx_ndt_score->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_score->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_score->setReadOnly(true);
        tx_ndt_score->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_ndt_ok = new QLabel(groupBox_other);
        lb_ndt_ok->setObjectName(QStringLiteral("lb_ndt_ok"));
        lb_ndt_ok->setGeometry(QRect(10, 160, 71, 17));
        tx_ndt_ok = new QTextEdit(groupBox_other);
        tx_ndt_ok->setObjectName(QStringLiteral("tx_ndt_ok"));
        tx_ndt_ok->setGeometry(QRect(60, 150, 41, 31));
        tx_ndt_ok->setAutoFillBackground(true);
        tx_ndt_ok->setLineWidth(0);
        tx_ndt_ok->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_ok->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_ndt_ok->setReadOnly(true);
        tx_ndt_ok->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_gnss_ok = new QLabel(groupBox_other);
        lb_gnss_ok->setObjectName(QStringLiteral("lb_gnss_ok"));
        lb_gnss_ok->setGeometry(QRect(110, 160, 71, 17));
        tx_gnss_ok = new QTextEdit(groupBox_other);
        tx_gnss_ok->setObjectName(QStringLiteral("tx_gnss_ok"));
        tx_gnss_ok->setGeometry(QRect(170, 150, 41, 31));
        tx_gnss_ok->setAutoFillBackground(true);
        tx_gnss_ok->setLineWidth(0);
        tx_gnss_ok->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_ok->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_gnss_ok->setReadOnly(true);
        tx_gnss_ok->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_localizer_select = new QLabel(tab);
        lb_localizer_select->setObjectName(QStringLiteral("lb_localizer_select"));
        lb_localizer_select->setGeometry(QRect(10, 520, 101, 17));
        tx_localizer_select = new QTextEdit(tab);
        tx_localizer_select->setObjectName(QStringLiteral("tx_localizer_select"));
        tx_localizer_select->setGeometry(QRect(90, 510, 251, 31));
        tx_localizer_select->setAutoFillBackground(true);
        tx_localizer_select->setLineWidth(0);
        tx_localizer_select->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_localizer_select->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_localizer_select->setReadOnly(true);
        tx_localizer_select->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_localizer_match_stat = new QTextEdit(tab);
        tx_localizer_match_stat->setObjectName(QStringLiteral("tx_localizer_match_stat"));
        tx_localizer_match_stat->setGeometry(QRect(90, 540, 251, 31));
        tx_localizer_match_stat->setAutoFillBackground(true);
        tx_localizer_match_stat->setLineWidth(0);
        tx_localizer_match_stat->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_localizer_match_stat->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_localizer_match_stat->setReadOnly(true);
        tx_localizer_match_stat->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_localizer_match_stat = new QLabel(tab);
        lb_localizer_match_stat->setObjectName(QStringLiteral("lb_localizer_match_stat"));
        lb_localizer_match_stat->setGeometry(QRect(10, 550, 101, 17));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget->addTab(tab_2, QString());
        bt_emergency_clear = new QPushButton(centralWidget);
        bt_emergency_clear->setObjectName(QStringLiteral("bt_emergency_clear"));
        bt_emergency_clear->setGeometry(QRect(10, 0, 101, 25));
        gb_shift = new QGroupBox(centralWidget);
        gb_shift->setObjectName(QStringLiteral("gb_shift"));
        gb_shift->setEnabled(false);
        gb_shift->setGeometry(QRect(720, 60, 311, 151));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_shift->setPalette(palette6);
        gb_shift->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_shift->setAcceptDrops(false);
        gb_shift->setAutoFillBackground(true);
        gb_shift->setFlat(false);
        gb_shift->setCheckable(false);
        bt_shift_P = new QPushButton(gb_shift);
        bt_shift_P->setObjectName(QStringLiteral("bt_shift_P"));
        bt_shift_P->setEnabled(false);
        bt_shift_P->setGeometry(QRect(40, 30, 51, 51));
        QFont font1;
        font1.setPointSize(18);
        bt_shift_P->setFont(font1);
        bt_shift_R = new QPushButton(gb_shift);
        bt_shift_R->setObjectName(QStringLiteral("bt_shift_R"));
        bt_shift_R->setEnabled(false);
        bt_shift_R->setGeometry(QRect(100, 30, 51, 51));
        bt_shift_R->setFont(font1);
        bt_shift_D = new QPushButton(gb_shift);
        bt_shift_D->setObjectName(QStringLiteral("bt_shift_D"));
        bt_shift_D->setGeometry(QRect(220, 30, 51, 51));
        bt_shift_D->setFont(font1);
        bt_shift_N = new QPushButton(gb_shift);
        bt_shift_N->setObjectName(QStringLiteral("bt_shift_N"));
        bt_shift_N->setGeometry(QRect(160, 30, 51, 51));
        bt_shift_N->setFont(font1);
        bt_shift_4 = new QPushButton(gb_shift);
        bt_shift_4->setObjectName(QStringLiteral("bt_shift_4"));
        bt_shift_4->setGeometry(QRect(100, 90, 51, 51));
        bt_shift_4->setFont(font1);
        bt_shift_2L = new QPushButton(gb_shift);
        bt_shift_2L->setObjectName(QStringLiteral("bt_shift_2L"));
        bt_shift_2L->setGeometry(QRect(160, 90, 51, 51));
        bt_shift_2L->setFont(font1);
        gb_velocity = new QGroupBox(centralWidget);
        gb_velocity->setObjectName(QStringLiteral("gb_velocity"));
        gb_velocity->setEnabled(false);
        gb_velocity->setGeometry(QRect(720, 240, 311, 91));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush8);
        gb_velocity->setPalette(palette7);
        gb_velocity->setContextMenuPolicy(Qt::DefaultContextMenu);
        gb_velocity->setAcceptDrops(false);
        gb_velocity->setAutoFillBackground(true);
        gb_velocity->setFlat(false);
        gb_velocity->setCheckable(false);
        spin_velocity_input = new QSpinBox(gb_velocity);
        spin_velocity_input->setObjectName(QStringLiteral("spin_velocity_input"));
        spin_velocity_input->setEnabled(false);
        spin_velocity_input->setGeometry(QRect(60, 30, 61, 26));
        hS_velocity_input = new QSlider(gb_velocity);
        hS_velocity_input->setObjectName(QStringLiteral("hS_velocity_input"));
        hS_velocity_input->setEnabled(false);
        hS_velocity_input->setGeometry(QRect(10, 70, 160, 16));
        hS_velocity_input->setOrientation(Qt::Horizontal);
        lb_velocity_target = new QLabel(gb_velocity);
        lb_velocity_target->setObjectName(QStringLiteral("lb_velocity_target"));
        lb_velocity_target->setGeometry(QRect(180, 30, 101, 17));
        tx_velocity_target = new QTextEdit(gb_velocity);
        tx_velocity_target->setObjectName(QStringLiteral("tx_velocity_target"));
        tx_velocity_target->setGeometry(QRect(230, 30, 71, 21));
        tx_velocity_target->setLineWidth(0);
        tx_velocity_target->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_target->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_target->setReadOnly(true);
        tx_velocity_target->setTextInteractionFlags(Qt::TextSelectableByMouse);
        tx_velocity_actual = new QTextEdit(gb_velocity);
        tx_velocity_actual->setObjectName(QStringLiteral("tx_velocity_actual"));
        tx_velocity_actual->setGeometry(QRect(230, 60, 71, 21));
        tx_velocity_actual->setLineWidth(0);
        tx_velocity_actual->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_actual->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tx_velocity_actual->setReadOnly(true);
        tx_velocity_actual->setTextInteractionFlags(Qt::TextSelectableByMouse);
        lb_velocity_actual = new QLabel(gb_velocity);
        lb_velocity_actual->setObjectName(QStringLiteral("lb_velocity_actual"));
        lb_velocity_actual->setGeometry(QRect(180, 60, 101, 17));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1066, 28));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox_drive->setTitle(QApplication::translate("MainWindow", "DRIVE_INFOMATION", nullptr));
        lb_drive_mode->setText(QApplication::translate("MainWindow", "mode", nullptr));
        lb_drive_control_mode->setText(QApplication::translate("MainWindow", "control_mode", nullptr));
        lb_drive_input_mode->setText(QApplication::translate("MainWindow", "input mode", nullptr));
        bt_drive_mode_manual->setText(QApplication::translate("MainWindow", "manual", nullptr));
        bt_drive_mode_program->setText(QApplication::translate("MainWindow", "program", nullptr));
        bt_drive_control_mode_velocity->setText(QApplication::translate("MainWindow", "velocity", nullptr));
        bt_drive_control_mode_stroke->setText(QApplication::translate("MainWindow", "stroke", nullptr));
        bt_drive_input_mode_direct->setText(QApplication::translate("MainWindow", "direct", nullptr));
        bt_drive_input_mode_autoware->setText(QApplication::translate("MainWindow", "auto", nullptr));
        gb_stroke->setTitle(QApplication::translate("MainWindow", "Stroke", nullptr));
        lb_stroke_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_stroke_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
        lb_drive_clutch->setText(QApplication::translate("MainWindow", "clutch", nullptr));
        bt_drive_clutch_cut->setText(QApplication::translate("MainWindow", "cut", nullptr));
        bt_drive_clutch_connect->setText(QApplication::translate("MainWindow", "connect", nullptr));
        groupBox_other_2->setTitle(QApplication::translate("MainWindow", "OTHER_INFOMATION", nullptr));
        lb_waypoint_num->setText(QApplication::translate("MainWindow", "way_num", nullptr));
        lb_stroke_routine->setText(QApplication::translate("MainWindow", "routine", nullptr));
        lb_yaw->setText(QApplication::translate("MainWindow", "yaw", nullptr));
        lb_roll->setText(QApplication::translate("MainWindow", "roll", nullptr));
        lb_pitch->setText(QApplication::translate("MainWindow", "pitch", nullptr));
        groupBox_steer->setTitle(QApplication::translate("MainWindow", "STEER_INFOMATION", nullptr));
        lb_steer_mode->setText(QApplication::translate("MainWindow", "mode", nullptr));
        lb_steer_input_mod->setText(QApplication::translate("MainWindow", "input mode", nullptr));
        bt_steer_mode_manual->setText(QApplication::translate("MainWindow", "manual", nullptr));
        bt_steer_mode_program->setText(QApplication::translate("MainWindow", "program", nullptr));
        bt_steer_input_mode_direct->setText(QApplication::translate("MainWindow", "direct", nullptr));
        bt_steer_input_mode_autoware->setText(QApplication::translate("MainWindow", "auto", nullptr));
        gb_angle->setTitle(QApplication::translate("MainWindow", "angle", nullptr));
        lb_angle_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_angle_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
        lb_steer_clutch->setText(QApplication::translate("MainWindow", "clutch", nullptr));
        bt_steer_clutch_cut->setText(QApplication::translate("MainWindow", "cut", nullptr));
        bt_steer_clutch_connect->setText(QApplication::translate("MainWindow", "connect", nullptr));
        groupBox_other->setTitle(QApplication::translate("MainWindow", "OTHER_INFOMATION", nullptr));
        lb_blinker_right->setText(QApplication::translate("MainWindow", "blinker_right", nullptr));
        bt_blinker_right_on->setText(QApplication::translate("MainWindow", "ON", nullptr));
        bt_blinker_right_off->setText(QApplication::translate("MainWindow", "OFF", nullptr));
        lb_blinker_left->setText(QApplication::translate("MainWindow", "blinker_left", nullptr));
        bt_blinker_left_on->setText(QApplication::translate("MainWindow", "ON", nullptr));
        bt_blinker_left_off->setText(QApplication::translate("MainWindow", "OFF", nullptr));
        lb_error_text->setText(QApplication::translate("MainWindow", "error text", nullptr));
        bt_error_text_reset->setText(QApplication::translate("MainWindow", "error clear", nullptr));
        lb_stopper_distance->setText(QApplication::translate("MainWindow", "stopD", nullptr));
        lb_can_jurk->setText(QApplication::translate("MainWindow", "jurk", nullptr));
        lb_can_velocity->setText(QApplication::translate("MainWindow", "vel", nullptr));
        lb_can_accel->setText(QApplication::translate("MainWindow", "acc", nullptr));
        lb_lat->setText(QApplication::translate("MainWindow", "lat", nullptr));
        lb_lon->setText(QApplication::translate("MainWindow", "lon", nullptr));
        lb_alt->setText(QApplication::translate("MainWindow", "alt", nullptr));
        lb_ndt_score->setText(QApplication::translate("MainWindow", "ndt score", nullptr));
        lb_ndt_ok->setText(QApplication::translate("MainWindow", "ndtOK", nullptr));
        lb_gnss_ok->setText(QApplication::translate("MainWindow", "gnssOK", nullptr));
        lb_localizer_select->setText(QApplication::translate("MainWindow", "localizer", nullptr));
        lb_localizer_match_stat->setText(QApplication::translate("MainWindow", "match stat", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Tab 1", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Tab 2", nullptr));
        bt_emergency_clear->setText(QApplication::translate("MainWindow", "\345\256\211\345\205\250\346\251\237\350\203\275\350\247\243\351\231\244", nullptr));
        gb_shift->setTitle(QApplication::translate("MainWindow", "Shift", nullptr));
        bt_shift_P->setText(QApplication::translate("MainWindow", "P", nullptr));
        bt_shift_R->setText(QApplication::translate("MainWindow", "R", nullptr));
        bt_shift_D->setText(QApplication::translate("MainWindow", "D", nullptr));
        bt_shift_N->setText(QApplication::translate("MainWindow", "N", nullptr));
        bt_shift_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        bt_shift_2L->setText(QApplication::translate("MainWindow", "2/L", nullptr));
        gb_velocity->setTitle(QApplication::translate("MainWindow", "Velocity", nullptr));
        lb_velocity_target->setText(QApplication::translate("MainWindow", "target", nullptr));
        lb_velocity_actual->setText(QApplication::translate("MainWindow", "actual", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
