(cl:in-package autoware_can_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          EMERGENCY-VAL
          EMERGENCY
          STEER_AUTO-VAL
          STEER_AUTO
          DRIVE_AUTO-VAL
          DRIVE_AUTO
          DRIVE_MODE-VAL
          DRIVE_MODE
          VELOCITY-VAL
          VELOCITY
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          PEDAL-VAL
          PEDAL
          EMERGENCY_STOP-VAL
          EMERGENCY_STOP
          ENGINE_START-VAL
          ENGINE_START
          IGNITION-VAL
          IGNITION
          WIPER-VAL
          WIPER
          LIGHT_HIGH-VAL
          LIGHT_HIGH
          LIGHT_LOW-VAL
          LIGHT_LOW
          LIGHT_SMALL-VAL
          LIGHT_SMALL
          HORN-VAL
          HORN
          HAZARD-VAL
          HAZARD
          BLINKER_RIGHT-VAL
          BLINKER_RIGHT
          BLINKER_LEFT-VAL
          BLINKER_LEFT
          SHIFT-VAL
          SHIFT
          SIDE_BRAKE-VAL
          SIDE_BRAKE
          AUTOMATIC_DOOR-VAL
          AUTOMATIC_DOOR
          READ_COUNTER-VAL
          READ_COUNTER
))